steps:
  - name: 'ubuntu'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          echo "=== Starting Python hello.py"
          python hello.py
          echo "=== Finished hello.py"

options:
  logging: CLOUD_LOGGING_ONLY
  #logging: NONE

logsBucket: gs://gcp-devops-course-bucket-new
